fieldLayouts:
  383357ca-80dc-461b-9822-10e1d6efb116:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Full Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 392ba5ea-479a-4155-a572-981e45604939
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a18cbd4-110b-40c0-8f03-458cd61a1393 # First Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d3ece5b-7eba-4647-9bd7-1548274c9ed2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dfe4ba04-8dd6-40a3-a1dc-504f24635aae # Last Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9de42fd4-4d86-4290-8cc3-91a7c30c2f10
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f0362c79-d0f0-4117-9cda-ff55e0c50a97 # Profile Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e3854aa-3e27-4761-bd33-3027b577e8a0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Details
            type: craft\fieldlayoutelements\Heading
            uid: dddef1da-05be-4f18-9242-3e86b402bebe
            userCondition: null
          -
            elementCondition: null
            fieldUid: 7d39b47a-b0da-4878-a45f-568644477e71 # Department
            instructions: null
            label: 'Departments, Offices, or Teams'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eba53ab6-c3c2-4860-a5b1-721435e35887
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 95eb654d-2231-4f49-b0c5-2a1c9c1eebe9 # Job Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88a9d5dc-2404-4ccb-a7f2-ee1522c9f9f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ccff731-9c55-4c1e-bf91-b7455841c132 # Pronouns
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00b8da5e-6e74-4343-9ed0-914ad1fe1468
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Contact
            type: craft\fieldlayoutelements\Heading
            uid: dac5f33d-d101-4209-9b5c-cd582eb984c2
            userCondition: null
          -
            elementCondition: null
            fieldUid: f9c6c299-6015-4673-8929-99f531e499cd # Contact Email
            instructions: null
            label: Email
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00717020-fb1d-47d2-b274-62f9800cf155
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 433a13e8-c868-4aad-a175-6de98725d1ee # Contact Phone
            instructions: "Use dashes _(\"-\")_ to delineate portions of a phone number for accessibility with screen readers. **Do not** user periods _(\".\")_, spaces, or other characters.  \r\n❌ ~~`301.405.4680`~~ _Fails Accessibility screening_.  \r\n✅ `301-405-4680`\__Passes Accessibility screening_.  "
            label: Phone
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31d67d04-c404-40b7-a3d5-0197643f2a6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: About
            type: craft\fieldlayoutelements\Heading
            uid: 55934a7e-43e1-4723-ab38-1000659e65ed
            userCondition: null
          -
            elementCondition: null
            fieldUid: e4d64cf3-ac5c-455d-a2a1-10950876b358 # About
            instructions: null
            label: Bio
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7730a51c-ea67-4ba7-8e15-ffcfbdb93923
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff9e5095-ce09-4c49-8f21-31bc8b0244d1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d1fe7761-d948-41f4-8400-3fabbe53501c # Leadership
            instructions: null
            label: 'Is Leadership'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1db1a6a4-e0d4-48b4-a207-991cbef66700
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4c6823dd-d7ae-4a66-9126-5feabbcfa6a6 # Vice President
            instructions: null
            label: 'Is Vice President'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b112e5-9eb4-48e0-9bb2-8ee7c65d6d37
            userCondition: null
            warning: null
            width: 100
        name: Leadership
        uid: 722ba534-11f9-4276-bb20-48917566688d
        userCondition: null
handle: person
hasTitleField: false
name: Person
section: e62abf0b-5f0f-4e1f-bbfd-4bd1480e192f # People
sortOrder: 1
titleFormat: '{ lastName ? lastName ~ ", " : "" }{ firstName ? firstName : "" }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
