columnSuffix: cfhfxzll
contentColumnType: text
fieldGroup: 82c2f2b8-a744-4155-aa61-43f9f1c1eb5d # Common
handle: email
instructions: null
name: 'Contact Email'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: email@umd.edu
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
