columnSuffix: gqtltacf
contentColumnType: string
fieldGroup: 82c2f2b8-a744-4155-aa61-43f9f1c1eb5d # Common
handle: vicePresident
instructions: null
name: 'Vice President'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'No'
        -
          - value
          - 'no'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Yes'
        -
          - value
          - 'yes'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
